name: model-training
on: [push]
jobs:
  run:
    needs: deploy-runner
    runs-on: [self-hosted,cml-runner]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.7'
      - uses: iterative/setup-dvc@v1
      - name: Pull the dataset
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: dvc pull
      - name: Check Dataset files existence
        id: check_dataset_files
        uses: andstor/file-existence-action@v1
        with:
          files: "aclImdb_v1.tar.gz"
      - uses: iterative/setup-cml@v1
      - name: Train model
        if: steps.check_dataset_files.outputs.files_exists == 'true'
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python text_classification.py
          cat metrics.txt >> report.md
          cml-publish plot.png --md >> report.md
          cml-send-comment report.md
